# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('api_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('summary', models.TextField()),
                ('score', models.FloatField(default=0)),
                ('n_reviews', models.IntegerField(default=0)),
                ('genres', models.TextField()),
                ('platforms', models.TextField()),
                ('cover_img', models.URLField()),
            ],
        ),
    ]
