# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 22:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('api_id', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('n_reviews', models.IntegerField(default=0)),
            ],
        ),
    ]
