# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 01:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='score',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
